### ISSUE TITLE
variables containing predicates are not displayed correctly.

### ISSUE THREAD

**Issue by harshakokel** [racket/racklog#20]
Consider the following example from the racklog [doc](https://docs.racket-lang.org/racklog/meta.html).

```
> (%which (p)
    (%member p (list %computer-literate %compound))
    (%odyssean p))
'((p . #<procedure:%computer-literate>))
```

I get `'((p . #<procedure:relation>))` instead of `'((p . #<procedure:%computer-literate>))`

**Comment by jeapostrophe** [comment]
The documentation is not a promise on this point. The compiler gives its best effort to preserve and record names like that but we can't be sure they will survive in the presence of optimization and code transformations.

**Comment by harshakokel** [comment]
Is there any other way to read or identify the variable?

**Comment by jeapostrophe** [comment]
If a variable is bound to a function, the only way to identify it is to call it. You are interested in the idea of extensionality --- https://en.wikipedia.org/wiki/Extensionality

**Comment by harshakokel** [comment]
There is a subtle difference between functions and relational predicates. But it looks like Racklog implements predicates as function and hence identifying the variable bound to a predicate relates to the idea of extensionality. But I am really looking for second-order logic https://en.wikipedia.org/wiki/Second-order_logic.
